// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNews() {
  return window['go']['news']['NewsFunctions']['GetNews']();
}

export function GetNewsDetails(arg1) {
  return window['go']['news']['NewsFunctions']['GetNewsDetails'](arg1);
}
