// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetNews():Promise<Array<models.News>>;

export function GetNewsDetails(arg1:string):Promise<models.NewsDetails>;
