// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateUser(arg1) {
  return window['go']['auth']['AuthFunctions']['AuthenticateUser'](arg1);
}

export function IsAuthed() {
  return window['go']['auth']['AuthFunctions']['IsAuthed']();
}

export function RemoveUser() {
  return window['go']['auth']['AuthFunctions']['RemoveUser']();
}
