// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetKNUSTStatus():Promise<Array<models.KNUSTServer>>;

export function GetStatusBadge():Promise<string>;
