// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKNUSTStatus() {
  return window['go']['status']['StatusFunctions']['GetKNUSTStatus']();
}

export function GetStatusBadge() {
  return window['go']['status']['StatusFunctions']['GetStatusBadge']();
}
