// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetUserData(arg1:string):Promise<models.UserData>;

export function GetUserImage(arg1:string):Promise<Array<number>>;
