// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion():Promise<string>;

export function ViewLink(arg1:string):Promise<void>;
